### ISSUE TITLE
Link posix threads library in HPC-GAP build

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#10]
Probably needs to be tested for as well.

**Comment by markuspf** [comment]
Would we use `AX_PTHREAD` (http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_pthread.m4), or just a plain lib test for this?

**Comment by fingolfin** [comment]
If `AX_PTHREAD` works, I see no reason not to use it. It's probably the easiest and quickest way to get pthread detection; and we can still write our own, should we decide at some point that we should / need to.

**Comment by fingolfin** [comment]
There's still a link error on Linux

**Comment by fingolfin** [comment]
OK, this is now resolved for good -- at least on Linux; on OS X, no special flags were needed anyway; I have no idea about BSD, but am hopeful @markuspf will report any remaining issues with that ;-).
