### ISSUE TITLE
Confusing error message when using apple's libtool 

### ISSUE THREAD

**Issue by ChrisJefferson** [fingolfin/gap#102]
I decided to try building from a plain mac os x install (with xcode)

Firstly I had to add `autoconf` and `automake` to get `autogen.sh` to run.

Then I get the following output from `./autogen.sh`:

```
+ rm -rf aclocal.m4 autom4te.cache cnf/ltmain.sh 'cnf/m4/l*.m4'
++ dirname ./autogen.sh
+ autoreconf -vif --no-recursive -I cnf/m4 .
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I cnf/m4 --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --include=cnf/m4 --force
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --include=cnf/m4 --force
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
```

and then the following error from the configure script:

```
...
checking whether g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... cnf/install-sh -c -d
./configure: line 4668: syntax error near unexpected token `2.4.2'
./configure: line 4668: `LT_PREREQ(2.4.2)'
```

To fix this, I have to re-run `./autogen.sh`, even if I run `brew install libtool`

**Comment by fingolfin** [comment]
The error message here is a bit confusing, this has nothing to do with Apple's libtool (which in turn has nothing to do with GNU libtool), and all with `(g)libtoolize` missing. In any case, this should be resolved by 97560909408bc3d12b25dba8d7f721f445564ff4
