### ISSUE TITLE
Move code out of src/hpc/boehm_gc.h into new file src/hpc/boehm_gc.c ?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#105]
Right now, most (all?) the glue code which provides a GASMAN-like interface to Boehm GC is inside the header file `src/hpc/boehm_gc.h`. This header is only included in one place, namely inside `src/gasman.c`, when HPC-GAP is enabled.

I would prefer if this code was in a separate `src/hpc/boehm_gc.c` file, at least most of it.

**Comment by ChrisJefferson** [comment]
There was a good reason for this (I did it), which was to try to keep the diffs as small as possible. I agree this code could be much better arranged -- in particular that isn't a "real header", as it can't be included in two files at once!

However, I think it would be easier to wait until after the build system merge, then start cleaning up.

**Comment by fingolfin** [comment]
Oh, of course -- I am using this tracker to log all things I notice while looking at the code; only things in the "merge" milestone" are intended to be done before the merge (and even those might be postponed till after).

Once the merge has happened, we can transfer any remaining open issues here to the main GAP tracker. But until then, I didn't want to spam it with random observations and notes.

**Comment by fingolfin** [comment]
Migrated to https://github.com/gap-system/gap/issues/1272
