### ISSUE TITLE
Unify / merge `GlobalState` and `ThreadLocalStorage`

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#106]
These two structs from `src/globalstate.h` and `src/hpc/tls.h` contain mostly the same content; of course the former was created as a way to migrate the latter from HPC-GAP to plain GAP. But right now, this migration is quite incomplete, and now we have these two similar-but-incompatible structs coexisting... This needs to be resolved.

Perhaps the two structs can be merged into one. Or perhaps one should always be a "superset" of the other -- then we can realize this via nesting (as poor man's substitute for class inheritance).

**Comment by markuspf** [comment]
I can do this.

**Comment by markuspf** [comment]
For more background: These structs actually contain exactly the same global variables; I just felt that "ThreadLocalStorage" was a bit of a misnomer for GAP (and it would probably have caused some discomfort with GAP developers.)

As a next step we should think about splitting this massive struct into smaller ones, because as is obvious from the header it collects global variables from different modules.

**Comment by fingolfin** [comment]
Actually, `GlobalState` and `ThreadLocalStorage` are not identical (even after I synced them in the PR): `ThreadLocalStorage` has many additional, threading specific variables. Moreover, the types of several members (e.g. `InputFiles` and `OutputFiles`) differ.  But of course this could be taken care of with some #ifdef... Yet I am not 100% this is what should do. Which is why I brought up the possibility of aggregation / inheritance: We could change the definition of `ThreadLocalStorage` to something like this:
```C
typedef struct ThreadLocalStorage
{
  int threadID;
  void *threadLock;
  void *threadSignal;
  void *acquiredMonitor;
  unsigned multiplexRandomSeed;
  void *currentRegion;
  void *threadRegion;
  void *traversalState;
  Obj threadObject;
  Obj tlRecords;
  Obj lockStack;
  int lockStackPointer;
  Obj copiedObjs;
  Obj interruptHandlers;
  void *CurrentHashLock;
  char *CurrFuncName;
  int DisableGuards;

  GlobalState globals;  // add in all GAP globals
  void *Extra[TLS_NUM_EXTRA];
} ThreadLocalStorage;
```

At the same time, let's replace the global `TLS` macro and its uses  by a new one, say `GLOBAL`, which is less confusing to non-HPC-GAP developers. Then define the `TLS` macro only in HPC-GAP, and only use it for threading specific stuff. So HPC-GAP, we would roughly do this
```
#define TLS(x) realTLS->x
#define GLOBAL(x) realTLS->global->x
```

Of course, we'd still have to add some `#ifdef HPCGAP` to `GlobalState` to deal with the globals which changed type -- though hopefully, we'll be able to get rid of that again over time, as more code is merged..

**Comment by fingolfin** [comment]
@markuspf You said you can do this -- that would be great! It's one of the big blockers for https://github.com/gap-system/gap/issues/1216

**Comment by fingolfin** [comment]
This has been done by @markuspf
