### ISSUE TITLE
Fix hpcgap/doc/hpc to use GAPDoc ManSection etc. for functions

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#109]
Right now, the manual in `hpcgap/doc/hpc` uses plain `Section` elements to document functions. It should be using `ManSection`s with nested `Description` and `Func`/`Oper`/... elements in it instead.

**Comment by olexandr-konovalov** [comment]
Oh yes. It was converted automatically, thanks to @jfdm, from a different format it which it was written before. Still requires some ironing.

**Comment by fingolfin** [comment]
Migrated to https://github.com/gap-system/gap/issues/1215
