### ISSUE TITLE
Do we want to bundle boehm-gc?

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#11]
One of the reasons that Reimer bundled boehm-gc was that we can supply different compilation options to its build (for example to enable parallel marking).

We'll have to find out what advantages these options give (or which negative effects a "badly" configured version of the Boehm-GC on the OS of the day can have).

**Comment by ChrisJefferson** [comment]
Also, I think we have private patches which might not be in any release...

**Comment by fingolfin** [comment]
Well, it would be good to explicitly know those private patches, and also check whether any of them could be upstreamed.

**Comment by fingolfin** [comment]
Seems the patches are https://github.com/gap-system/gap/blob/hpcgap-default/extern/gc-7.4.2-tl.patch and https://github.com/gap-system/gap/blob/hpcgap-default/extern/gc-7.4.2-conf.patch

Also, there are Boehm GC 7.4.4 and 7.6.0 releases, newer than what we currently have in hpcgap-default.

**Comment by fingolfin** [comment]
The configure patch that makes it recognize dragonbsd seems like something that could and should be upstreamed. Of course properly (i.e. as change to `configure.ac` and `CMakeLists.txt`, not to `configure`)

**Comment by fingolfin** [comment]
I don't understand the change to the `__clang_major__` check in `gc_config_macros.h`...

**Comment by ChrisJefferson** [comment]
The **clang_major** is working around an issue where Apple's clang version numbers drifted out of sync with the offical ones. It looks to me like everything in the configure script patch is fixed in 7.6.0 (or alternatively, handled in another way) (there is mention of dragonfly for example, so I'm assuming it works...)

**Comment by ChrisJefferson** [comment]
The only bit that really worried me is the `GC_INNER mse GC_local_mark_stacks[MAX_MARKERS+1][LOCAL_MARK_STACK_SIZE];`.. I have no idea what that does...

**Comment by markuspf** [comment]
dragonfly does not work with 7.6.0 from github, but I can easily submit a patch to the boehm-gc people to make that change. I am actually surprised that that hasn't happened yet...

**Comment by fingolfin** [comment]
So for now I guess we'll have to bundle gc, and since we are doing that anyway, we can also bundle libatomic.

**Comment by fingolfin** [comment]
Resolution of this issue: Yes, we want to bundle it for now (though we also want to allow people to use a system installed version of Boehm GC, see issue #56 and #59.
