### ISSUE TITLE
Document the plain `Makefile`, and make sure it actually works on BSD systems

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#13]
There are two major variants of make: GNU make, and BSD make. They both started from the same base, but developed in different directions.

Our new build system is written for GNU make, and makes use of its extensions. Hence it is incompatible with BSD make. This can lead to weird errors for BSD users when they type in `make`. To workaround that, the actual build system is in `GNUmakefile`, which only GNU make reads (and prefers over any plain `Makefile`); and `Makefile` contains dummy code, which only BSD make should execute, and which right now simply tells the user to run GNU make (by typing `gmake`).

@markuspf tells me that the latter does not actually work on BSD make right now... I don't have access to a system with BSD make, so I can't test myself. It would be good to get this fixed. A simple "fix" would be to change the file to have a simple `all:` target which prints the error. But then `make foo` for any value of `foo` other than `all` would not print the nice warning. This is why I added a `.DEFAULT` target, which I thought would do the job... apparently I am mistaken. Huh.

**Comment by ChrisJefferson** [comment]
Weird, I just tried it on my installation of bsdmake (still on Mac admittedly), and it seems to work fine. Not sure what's wrong with it.

**Comment by fingolfin** [comment]
Markus fixed it in f53fc2f0b055ac8c189a34941a6cc3fcafe7ffea
