### ISSUE TITLE
Add manuals target

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#16]

**Comment by markuspf** [comment]
I'll have a go at this, seems like a good practising task.

**Comment by markuspf** [comment]
We have two choices here I think
- Generate the documentation in `doc` as before (and put generated and source files in the same directory etc), this is reasonably easy to do
- Clean up the generation of documentation and hence hack around `GAPDoc` to generate documentation in a directory different from the documentation source. This will be more work.

**Comment by fingolfin** [comment]
Is it worth the effort of "ahcking around GAPDoc" at this time? If being able to output the HTML etc. into a separate dir, then wouldn't it be better to improve GAPDoc suitably? Granted, we'd first have to get Frank to make a new GAPDoc release, but that's a separate problem... ;-)

**Comment by markuspf** [comment]
So, we do agree that we should be able to put generated documentation into some target directory that can be specified, and it should in particular not end up in the same directory as the source of the docs?

We'd also have to make sure that a GAP can then look in the correct place for the help system.

For backwards compatibilty we might be able to put the generated documentation into `doc/` and move the documentation source some place else?

**Comment by fingolfin** [comment]
For now, I think it's easiest if the "manuals" target puts the generated manual into $srcdir, not $builddir - while on the long run, I'd find the latter more logical and would prefer it, doing that requires either a change to GAPDoc, or tricks (such as copying or symlinking manual source files).

**Comment by fingolfin** [comment]
With 88f00a7dbe83525fa5086605b3339b3191bb35b2 one can use "make manuals" in an out-of-tree build. It still generates the manual inside srcdir. To change that would require a modified GAPDoc, or some gross hacking.

And some people might even prefer it if they only need to build the manual once, and all their GAP builds share it.

Anyway, this should be good enough for now.
