### ISSUE TITLE
Add new build mechanism for packages with kernel extensions 

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#18]

**Comment by markuspf** [comment]
Additional bonus: Implement custom package root dirs (independent of GAP root dirs)
  (Max already has a local branch implementing most of this)

**Comment by fingolfin** [comment]
For package dirs independent from GAP roots, see https://github.com/gap-system/gap/pull/933

**Comment by fingolfin** [comment]
This is a duplicate of issue #45 -- or rather, the other way around. But #45 is far more detailed, so I am keeping that one open.
