### ISSUE TITLE
Use cases to test

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#19]
Test several use cases:
- [ ] Single config, in-tree build
- [x] Single config, in-tree build in compatibility mode
- [ ] out-of-tree builds
- [x] out-of-tree builds in compatibility mode
- [ ] either of the above together with "make install"

**Comment by olexandr-konovalov** [comment]
Related to PR #55 and PR #61.

**Comment by fingolfin** [comment]
Actually all tests are in compatibility mode right now, as that is on by default. And we can't realy test with it off until there is a version of `io` (or other packages, for that matter) which works without compatibility mode. And `make install` has not yet been implemented.
