### ISSUE TITLE
Replace SyKernelVersion fully by SyBuildVersion

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#23]
Places where this might be problematic:

   1. The workspace handling code, which does a strict match on the
      version number; so workspaces would be broken with any commit...
      Which you might consider a bug or a feature...
   2. The code comparing the library and the kernel version.

   Both of the above issues are currently "solved" (or ignored, depending on how
   you look at it) by setting the kernel and library versions to "4.dev" in
   all non-release builds.
  
   Affected variables:
   - GAP.Version
   - GAP.NeedKernelVersion
   - GAPInfo.KernelVersion
   - GAPInfo.BuildVersion
   - GAPInfo.KernelInfo.KERNEL_VERSION
   - GAPInfo.KernelInfo.BUILD_VERSION

**Comment by fingolfin** [comment]
I don't really remember why I wanted to do this, but it doesn't really seem to be important, and not even worth of migrating to the GAP issue tracker.

So just closing it for now.
