### ISSUE TITLE
Update the copyright headers in all *.c and *.h files

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#24]
- remove obsolete refs to persons
  - update copyright for GAP group to 2002-2016
  - automate extending that copyright? Does it make sense to even have it then?
  - mention that the license is GPL 2 or later

**Comment by fingolfin** [comment]
Closing this, as it is not really an HPC-GAP or build system issue. Feel free to open a new similar issue at gap-system/gap, though.
