### ISSUE TITLE
Use stdint.h types.

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#25]
GAP uses the rather unusual convention that its typedefs "Int" and "UInt" take up 8 bytes on 64 bit systems, unlike "int" and "unsigned int", which usually stay at 4 bytes (32 bits).
  This can lead to very nasty bugs due to people not checking the definition of the type and then using it incorrectly.

  Instead, we should consider switching the whole codebase to use stdint.h types with explicit sizes, like int32_t, uint64_t, etc.

  Of course also more advanced types could be used, like this:
    uint_least32_t
    uint_fast32_t
    intptr_t
    intmax_t  (this might be the closes to our current "Int")
  
  and of course classics like

    ptrdiff_t
    size_t

**Comment by ChrisJefferson** [comment]
Most uses of `Int` are really "integer which fits a GAP small int / array size / permutation element", which does differ between 32-bit and 64-bit builds of GAP. I suspect if you did do away with Int, almost all of them would want to be `ptrdiff_t`, but I'm not sure if the gain would be worth the pain.

**Comment by fingolfin** [comment]
Note that in the `hpc-merge` branch, we essentially *are* using `stdint.h` types already thanks to the commit `system.h: remove old definitions of Char, Int1, Int2, ...`  (currently has id 4b334e1d66ed01d3594edb6a436e9112fe9159e2). It ensures that our custom types are defined in terms of stdint.h types.

The bigger change would be go through with a regex and replace , say, `UInt8` with `uint64_t` everywhere. We'd still have to keep the old types for compatibility with packages, though. Anywya, if we wanted to this, I'd be trivial to do this automatically as part of the `redo-merge.sh` script. Though I'd only do this for the `IntN` types, not for pure `Int` and `UInt`. The latter would have to be inspected carefully by hand...

Of course a more fine grained conversion, as @markuspf suggests it, would be possible, but it would also require a *lot* of work.

Anyway, if we were to do this, we should first bring it up on the gap mailing list, to ensure nobody has a major argument against it. Also, we'd have to explain why one should make the change, other than for change's sake. My personal argument would be that those types are immediately known to most C/C++ programmers, making it easier to for newcomers to help with kernel development.

A particular good ("bad"?) example for this are our current typenames `Int8` and `UInt8`: in every single other C/C++ project I know of, the 8 would indicate a number of bits, not bytes, which can be quite confusing, and lead to stupid mistakes.

**Comment by fingolfin** [comment]
Closing this, as it is not really an HPC-GAP or build system issue. Feel free to open a new similar issue at gap-system/gap, though.
