### ISSUE TITLE
What about HAVE_NATIVE_TLS

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#26]
This is an option that should not in general be used.

It is in general slower to use this, and it is mostly useful on architectures that have neither clang or gcc, and hence `__builtin_fram_address(0)` isn't accessible, and the portable alternative is slower or does not work correctly. 

Could also be useful for testing.

(Comment from @rbehrends, translated into english)

**Comment by rbehrends** [comment]
That is essentially still very close to the state of affairs. It's there to be used when it's needed for (1) portability (2) debugging or (3) on systems where there is an actual performance gain.

Native TLS support can be very slow on some architectures (macOS, Cygwin), and may or may not be more expensive on other architectures. That said, I'd like to benchmark both approaches on Linux with modern versions of gcc/clang and link-time optimization.

Briefly, what we do works as follows: Thread stacks get allocated on a segment where the base address (and size) is a multiple of 2^k for some k and thread-local storage is put at the beginning of the segment. Then, we take an address on the stack (the frame pointer or stack pointer), mask out the lowest k bits and use that as the base. This is generally very fast.

Native installations tend to use a segment register (`fs` or `gs`) on Intel architectures. This is either used directly as an offset – or as a reference to an area that contains pointers to thread-local storage. Figuring out the offset into the area can require an additional indirection when separate compilation is being used.

For example, here is what `++x` with `extern __thread int x` compiles to on Linux (x86_64, gcc 6.2.1):

```
        movq    x@gottpoff(%rip), %rax
        addl    $1, %fs:(%rax)
```

However, with link-time optimization, the additional indirection disappears, and it basically becomes:

```
   0x00000000004003e0 <+0>:     addl   $0x1,%fs:0xfffffffffffffffc
```

On some systems, TLS is further only accessible via a library call, adding significant overhead.

The downside of our approach is that all thread-local storage has to be packed into a single struct; the advantage is that its performance is good even on systems that have poor TLS support.

**Comment by markuspf** [comment]
Mhm. I should keep this in mind over the "global state" struct business, since the above seems to say that we need to keep Thread Local State in one struct.

**Comment by fingolfin** [comment]
Reading this, it seems to me that there is no immediate action that needs to be taken here. Rather, the `HAVE_NATIVE_TLS` just exists, and to use it one would have to explicitly `#define` it, say by passing `CPPFLAGS="-DHAVE_NATIVE_TLS"` to `configure`.

So this leaves the issue of actually documenting that possibility, and that seems to me the actual issue here: The description of `HAVE_NATIVE_TLS` above should be put into some file somewhere... perhaps into `hpcgap/README.tls` ?

**Comment by fingolfin** [comment]
Closed in favor of https://github.com/gap-system/gap/issues/1885
