### ISSUE TITLE
Remove ZeroMQ code, in favor of zeromq package

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#27]
Instead of trying to get the zeromq code integrated, I think I'd prefer to just remove it, and instead let people use the ZeroMQ package https://github.com/gap-packages/zeromq/

**Comment by fingolfin** [comment]
@markuspf does that sounds reasonable to you?

**Comment by markuspf** [comment]
Absolutely. I shlould have a look at the zeromq package at some point to make sure it works. Once I got the hang of this make system stuff I can make sure that package is detecting  zeromq etc.

**Comment by ChrisJefferson** [comment]
I agree, I don't see (having looked at this code in the past) at any advantage to it being in the kernel (of course, it might want some kernel functions to make it more efficient to package/unpacakge objects, but that isn't zeromq-specific).

**Comment by fingolfin** [comment]
Done in 58aa7e902e32c199b68c9e0af9b159aa74e06aee
