### ISSUE TITLE
HPC-GAP: which merge strategy should we use?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#36]
Last night, I looked again at the divergence between master and hpcgap-default.

A lot of it is relatively easy to resolve, and I started to generate a patch which reduces the diffs again to the "essentials". But then I stopped and wondered "am I doing the right thing here?"

Specifically, I see three ways forward with this:

1. We could try to perform a `git merge master` on `hpcgap-default`. I just tried, and it of courses has tons of conflicts.

2. We could "manually" reduce diffs on `hpcgap-default`, generating a big commits on that branch which reduces the diffs to master, but without actually doing a merge.

3. We could do the same as 2., but on the `hpc-merge` branch.

Each approach has its pros and cons:

Approach 1 on the surfaces seems to ensure we don't "miss" any changes. But I am actually not sure that's true: If an older merge did something wrong, and incorrectly applied or dropped some changes, then we won't be prompted for this again. Also, it's an "all or nothing" approach: In order to complete the merge, one has to resolve *all* the conflicts. While the few I looked at seemed easy enough to resolve, there are over 70 files with conflicts, so there is quite some effort required.

Approach 2 is easier in that it can be done more incrementally (though that still requires some effort, of course). It basically involves somebody looking at all diffs between files, one by one. A tedious process, but on the up side, it ensures the full actual diffs are considered, and not just some subset which is affected by previous merges. I already found a few (harmless) places were clearly previous merges had gone wrong (e.g. duplicated comments).

Approach 3 is as easy / hard as approach 2. It is a bit easier for me to maintain, *but* the big drawback is that it might easily break down if somebody starts to make changes on `hpcgap-default` again.

Right now, I tend towards approach 2. However, as either approach in the end will require hours and hours of work, I thought it best to write up my thoughts, to (a) clear the situation up in my mind, and (b) in the hops of some additional input, pointing out further alternatives, or pros and cons I did not think of.

**Comment by olexandr-konovalov** [comment]
Thanks @fingolfin for explaining all pros/contras. In brief, I think Approach 2 is the way to go indeed.

**Comment by markuspf** [comment]
I'll do whatever as long as we do it only exactly *once* more.

**Comment by ChrisJefferson** [comment]
I agree with @markuspf : I stopped trying to do merges some time ago, as it was difficult to test it was being done correctly, and it wasn't clear how long it would have to be done for.

Switching to approach 2 seems like a good plan, particularly because we want to move towards unifying the two code bases, so just looking at every place where they differ seems most sensible.

**Comment by fingolfin** [comment]
Despite all this, I attempted another regular merge (see https://github.com/gap-system/gap/pull/1020 ) for the following reason: A manual moving over is a one-way road: Once done, performing a merge afterwards becomes essentially impossible.

My plan for the final merge is to use that merge (which already involved lots of manual diffing) as foundation, and then, based on it, run a manual diff (as in approach 2) against master.

**Comment by fingolfin** [comment]
Making that diff, I also realized how painful it is that we are missing the old repository history. There are quite some changes in HPC-GAP for which I had to go back to their history to understand why they were made, and more for which I should have done it, but skipped it for now as it was too much work... *sigh*
