### ISSUE TITLE
Reactivate or remove Itanium support

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#38]
Itanium support is disabled in the new build system -- we ignore `src/itanium.s`. We should either reactive this, or else remove it (and all traces refering to itanium). As I see it, Itanium is dead, so I guess there is little need to keeping it. Alas, I might be wrong -- so, if we can find anybody who wants to use GAP on Itanium, I'd be happy to work with that person to reactive support.

But it doesn't make sense to do this without even a test machine...

**Comment by markuspf** [comment]
remove it.

**Comment by fingolfin** [comment]
done
