### ISSUE TITLE
Make gac work again

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#39]
Right now, the following package require gac to compiler their kernel extension:
* Browse
* edim
* Gauss

To support these packages, `gac` needs to work again.

In addition, HAP has some scripts to compile GAP code to C using gac, though that is optional.

See also #3 and #4

**Comment by markuspf** [comment]
What does "make gac work again" constitute? I'd be interested in/willing to do this.

**Comment by fingolfin** [comment]
There are different levels to this. The ultimate version would use `libtool` instead of hardcoding compiler flags. But this opens up other problems (e.g. for supporting `make install`, we might have to install a copy of `ltmain.sh`.

So a more realistic version would look like this (please also take a look at f2d3804bfd965a42b4e5b49fe89f8f21fce1f0c5 but feel free to ignore the libtool related changes)

* ensure `gac.in` gets converted to `gac` -- either by tweaking `configure.ac`, or `Makefile.rules`. The former is nice because it takes care of substitutions for you; however, doing them manually using `sed` is not hard, and note that you need to know how to substitute `@OBJECTS@` and that in turn is easier from `Makefile.rules` -- note that I really would prefer if we kept the list of source files in a single place, i.e. either in `configure.ac`, `Makefile.rules`, or a third place which is used by both. Hmm, thinking about it now, another alternative would be to create an `libgap.a` archive which contains all object files except `compstat.o`, and then change `gac` to have `OBJECTS=libgap.a` only... (Of course the name `libgap` might give a wrong impression, so perhaps use more innocous, like `gac-support.a` or so....

* BTW, note that the list of objects is *only* needed for static linking modules! And to be frank, I am not sure that's a very useful feature to begin with; so perhaps we might want to drop it altogether? However, dropping a feature like this might cause some people to be against the work on `hpc-merge`, so I'd rather not do it right now unless we really have a strong reason other than "it makes our life a tiny bit easier" ;-).

* Copy some of the old rules from `cnf/aclocal.m4` (on `master`) to a new file `cnf/m4/gac.m4` -- relevant are probably `GP_PROG_CC_EXPORT_DYNAMIC`, `GP_C_UNDERSCORE_SYMBOLS`, `GP_PROG_CC_DYNFLAGS`, and *perhaps* `GP_LDFLAGS`, though I hope it is not relevant (I don't know what the `-rdynamic` for clang is about, though, and the Darwin settings seem weird, and possible out-of-date...). 

* Of course a more radical course would be to start from scratch with those flags, and only add them back for systems as we get reports from people / as we have access to them so that we can test that things actually work...

* as I mentioned, an alternative (possible better for portability, on the long run?) is to use `libtool`... but as I also sketched, it involve a lot of headaches, and I am not yet convinced it is a good idea to start with: We might be better of removing the parts from `gac` which allow using it to create loadable modules, and instead require the three packages using `gac` for that to switch to a build system that uses `libtool`. I think this is the better solution, though it would require Frank and Thomas to collarborate with us in order to migrate `Browse` and `edim` (even if we send them patches... I have sent Frank Browse and GAPDoc patches years ago which are not yet in a release; and during the first GAP days, I converted Browse to a new autotools, sitting next to Frank to show him how to do it, and send him the result; so technically, it has already been done).

**Comment by fingolfin** [comment]
I made some progress on this in 5cd02f8a8901d1732f4e2e4f45b8581b856b6083

**Comment by fingolfin** [comment]
`gac` works more or less in current GAP master. It's still not quite what it should be, but it's "good enough"; we can edit specific issues as needed.
