### ISSUE TITLE
Compile conwdat1.g filter1.g  methsel1.g oper1.g  read1.g    type1.g to C

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#4]
Maybe we should also benchmark and establish how valuable this is?

**Comment by markuspf** [comment]
Having a bootstrap stage that compiles GAP without using the optimised versions of these files could be quite valuable, in particular with the changes between GAP and HPC-GAP.

**Comment by ChrisJefferson** [comment]
This is still valuable, at some point I put some work into fixing the compiler in HPC-GAP, so we could start compiling again. The dispatch stuff in particular goes quite a bit faster if compiled.

**Comment by markuspf** [comment]
Just compiling to C seems to be doable relatively easily once one figured out which magic incantations to use with `-C`.
Now I'll have to find out how to compile GAP in absence of the compiled files and still run it...

**Comment by fingolfin** [comment]
Note that `make docomp` in `hpc-merge` takes the place of `etc/docomp`, so that issue in the title of this issue should be resolved -- I assume, at least, as the body of this issue seems to be about differnt things?!
