### ISSUE TITLE
Update bundled libatomic to 7.4.4?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#41]
We currently bundle a version of libatomic from 2012-03-02 which is marked as 7.3alpha1. Perhaps we could switch to 7.4.4. But I am not sure if that is "safe", nor how to best test for regressions.

**Comment by fingolfin** [comment]
Perhaps @rbehrends could suggest something?

**Comment by rbehrends** [comment]
This should be unproblematic, but it should be the same libatomic_ops version that the GC uses.

**Comment by fingolfin** [comment]
Done.
