### ISSUE TITLE
Switch to libtool for compiling and linking?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#50]

**Comment by ChrisJefferson** [comment]
I'm neither in favour nor against.. I trust someone who knows more about libtool (you :) ) to know if would save a useful amount of work (I mean, don't we just link a bunch of C files together?)

**Comment by fingolfin** [comment]
First off, using libtool is an almost trivial change. Basically, we replace  `cc OPTIONS` with `libtool --mode=compile cc OPTIONS...` or `libtool --mode=link cc OPTIONS...`, depending on whether we invoked cc for compilatio or linking. That's it.

One reason for this is to allow us to bundle gmp, gc, libatomic_ops and use them without installing them -- since they use libtool, this is much, much easier if we also use libtool.  Indeed, without using libtool, the only portable option we have is to run `make install` in these packages, installing them into a fake prefix -- otherwise, the shared libraries in them are not usable. We could also force them to only build static libraries, but that in turn causes troubles with kernel extensions that need to use GMP, so it's a no-go.

But doing a `make install` into a fake prefix would create a big road block for us supporting `make install` (see issue #44).

The other reason is that libtool makes it trivial to create an executable that can be used together with loadable modules, and can also create loadable modules. It seems that on most currently used OSes, that's trivial, too, but it used to be different in the past, and may be different again in the future.

Point is, libtool takes care of handling all these things for us portably, across far more systems that we could manually support.


Of course, if we are happy to limit support of GAP to Windows, Mac OS X, Linux (and the ocassional stray extra, like DragonFlyBSD, for as long as there are dedicated individuals to cater to that particular system), this is not an argument. So this is a matter of what our goals are. And also whether we believe that the future is with just these three OSes (and perhaps fewer eventually), or whether we want to also try to cover the rest.

**Comment by ChrisJefferson** [comment]
I think the "it makes it easier to use extra libraries without installing them" is an excellent argument by itself, because as you say that has always been a little wobbly, and is one of the `make install` blocks I hit myself in the past, So I agree we should libtool.

**Comment by markuspf** [comment]
At the risk of "me too"-ing, I approve of this as well.

**Comment by fingolfin** [comment]
I implemented this now in 61de35eb4f36b0f0039fc3cb3239602974db2720 but realized that I forgot about one thing I hate about libtool: It compiles every file twice by default, i.e. it increases build time by a factor two: it compiles a version of every file for static linking, and dynamic linking.

I guess that used to make sense, but these days, we really always want the shared version... I'll see if I can get it to do that.

**Comment by fingolfin** [comment]
Actually, I take that back: On my system, it only compiles the shared version by default. So compile speeds should be fine, if that's the default everywhere.

I just measured compiliaton for master and hpcmerge on my system, and they more or less match.

Phew :-)
