### ISSUE TITLE
Can we remove `ReadGuardByRef` and `WriteGuardByRef`?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#54]
These two functions don't seem to be used, nor be generated by ward. Can we get rid of them?

@rbehrends might know.

**Comment by rbehrends** [comment]
They can probably be removed. The intent behind them was to support a few odd use cases where you would insert guards manually (such as when passing the reference to an object to a function without having to introduce temporaries), but I don't think it's worth the additional complexity.
