### ISSUE TITLE
Setup Travis/AppVeyor tests for build variants

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#55]
I just learnd that in-tree build were broken -- since I mostly test with out-of-tree builds, I did not notice.

To avoid similar problems, there should be systematic travis tests for the various ways to build things. Perhaps this build matrix
* in-tree vs. out-of-tree
* HPC-gap on/off
* 32 vs. 64 bit

**Comment by fingolfin** [comment]
Mind you, for now the tests would only test compilation, and perhaps some very light test (one that also work in hpc-gap)

**Comment by fingolfin** [comment]
Of course we also need an Appveyor test.

**Comment by olexandr-konovalov** [comment]
Seems to me that https://travis-ci.org/fingolfin/gap is already set up, the task is to modify `.travis.yml` to cover all combinations.

**Comment by olexandr-konovalov** [comment]
To remind myself: 
* add testing builds in HPC-GAP compatibility mode (invoked by `./configure --enable-hpcgap`) can be done later, although the sooner the better.
* add AppVeyor builds needed now, and also is required in #21.
