### ISSUE TITLE
Add configure flags `--with-atomic-ops=PATH` and `--with-boehm=PATH`

### ISSUE THREAD

**Issue by ChrisJefferson** [fingolfin/gap#56]
At the moment there is no way to tell configure where to find atomic-ops or gc

**Comment by fingolfin** [comment]
Based on the discussion that lead to this issue, I assume you man that flags `--with-atomic-ops=PATH` and `--with-boehm=PATH` should be added.

**Comment by fingolfin** [comment]
Also, we should have a test to check for the presence of either.

Note that we now build the bundled versions of both by default, but I think it's important to let people use external versions of both eventually...

**Comment by fingolfin** [comment]
This is related to issue #7.

It could wait till after the merge. Though I think it would be nice if we could do it before (and it shouldn't be hard).

**Comment by fingolfin** [comment]
Migrated to https://github.com/gap-system/gap/issues/1466
