### ISSUE TITLE
Add configure flag for selecting the garbage collector

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#59]
This might be an option `--with-gc=VALUE`, where `VALUE` currently could be `gasman` or `boehm` (and possibly also `none`). In the future, `julia` might be another possible value.

If HPC-GAP is disabled, then `gasman` would be default; if HPC-GAP is enabled, then `boehm`. But we'd want to allow `boehm` in regular GAP, too. As for `gasman`, I don't think it is thread safe, so for HPC-GAP we'd probably show an error that the two cannot be combined.

We could then also add a `--disable-masterpointer` configure flag, which is only allowed if the gc is `boehm`, `julia` or `none`, and which would try to get rid of as much "overhead" needed for GASMAN but not the other collectors as possible. E.g. with it, `ADDR_OBJ` might be much simpler, avoiding indirection. E.g. we might have
```
typedef struct {
  Header hdr; // header; could be a bitfield if necessary 
  void *data[];
} *Bag;

#define SIZE_BAG(o)  (o->hdr.size)
#define PTR_BAG(o)  (o->data)
```
etc., and then see how that affects performance.

**Comment by fingolfin** [comment]
Some notes to self: If the `--with-boehm=PATH` option is specified by the user, then likely this should also set `GC=boehm`. If the user also specified an explicit `--with-gc=gasman`, then ideally we'd report an error... Though that is extra complxity, so I might just skip that at first.

**Comment by fingolfin** [comment]
Is Boehm GC actually working in non-HPC-GAP right now?

@ChrisJefferson do you know?

**Comment by ChrisJefferson** [comment]
No, not yet. The only blocker (from memory) is automatic variables, which were just never implemented for Boehm. With some horrible hacking to remove enough automatic variables to get GAP to start, it will work with Boehm (or at least, it did).

**Comment by fingolfin** [comment]
Migrated to https://github.com/gap-system/gap/issues/1470
