### ISSUE TITLE
Complete HPC mode working

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#6]
Right now, hpc gap mode does not yet even compile. So the first step is to fix that. After that, it'll probably crash... :-)

Consider this issue as kind of a meta-issue, we can create more issues for specific problem.

I'll dump some random thoughts about things that need to be done here:
- in HPC-GAP mode, we want to automatically use two GAP root dirs: first `$(srcdir)/hpcgap/lib` and then (as fallback) `$(srcdir)/lib`
- there are lots of build settings in the old SCons based HPC-GAP build system; we may want to resurrect some. E.g. `gcblksize`

**Comment by fingolfin** [comment]
A first version of this is working now! But it still involves some hacks, so more work is needed.

**Comment by markuspf** [comment]
I'll test this some time this week.

**Comment by fingolfin** [comment]
So HPC-GAP mode mostly works now. We even build our own versions of Boehm GC and libatomic_ops. 

That said, there are a few optional settings of the old HPC-GAP build system we did not yet port, see #9.

**Comment by fingolfin** [comment]
Also, some tests for this should run and ideally pass. @alex-konovalov is working on that.

However, note that we currently have just a single `testinstall` set, and this actually may fail for now, due to unresolved diffs between `master` and `hpcgap-default` :-(

**Comment by fingolfin** [comment]
This is not strictly necessary for the merge, but would still be nice to have.
