### ISSUE TITLE
configure fails with -Werror

### ISSUE THREAD

**Issue by olexandr-konovalov** [fingolfin/gap#77]
```
checking for opendir... yes
checking for closedir... yes
checking for readdir... yes
checking for library containing cos... no
configure: error: unable to find the cos() function
Build step 'Execute shell' marked build as failure
```

**Comment by fingolfin** [comment]
By specifying `-Werror` in the CFLAGS passed to `configure`, you make all autoconf checks use that flag -- and many of them produce warnings as normal part of their operation. As a result, tons of those tests now fail -- and most fail silently, so what you are reporting here is just the tip of the iceberg.

I guess the proper way to support `-Werror` like that would be to have an `--enable-Werror` flag which adds `-Werror` to the (internal!) GAP_CFLAGS, but not the CFLAGS.

Or we could look into making it possible to write `make CFLAGS=-Werror` -- the tricky bit there is that currently the ABI_CFLAGS are added into CFLAGS as part of configure (to make the tests use them), and overriding CFLAGS when calling `make` will cause them to be lost... So for this, we might want to add the ABI_CFLAGS *again* in `Makefile.rules`.

**Comment by olexandr-konovalov** [comment]
Just to explain the context in which this appears: to adapt Jenkins tests which builds GAP with -Werrror option to check that there are no compiler warnings, this part of the script
```
if [ $GAPCOPTS = '64build' ]
then
./configure ABI=64 --with-readline=$FINDREADLINE
make config # ensure the inner configure is run, but do not build anything
make extern # build GMP
make COPTS=-Werror 
else
./configure ABI=32 --with-readline=$FINDREADLINE
make config 
make extern 
make COPTS=-Werror 
fi
```
has been changed to 
```
./autogen.sh
if [ $GAPCOPTS = '64build' ]
then
./configure ABI=64 CFLAGS=-Werror --with-readline=$FINDREADLINE
else
./configure ABI=32 CFLAGS=-Werror --with-readline=$FINDREADLINE
fi
make gmp
make V=1 
```

**Comment by fingolfin** [comment]
As discussed elsewhere (and I think also implemented) the above should be changed to this:
```
./autogen.sh
if [ $GAPCOPTS = '64build' ]
then
./configure ABI=64 --with-readline=$FINDREADLINE
else
./configure ABI=32 --with-readline=$FINDREADLINE
fi
make gmp
make CFLAGS=-Werror V=1
```
