### ISSUE TITLE
Implement `--enable-debug` configure flag

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#80]
Currently, `--enable-debug` does nothing. It should disable optimizations and ensure `-g` is set. Perhaps it should also do other things?

**Comment by ChrisJefferson** [comment]
I would love some kind of compile time assert we can turn on in C code. However, we can always add that later (in particular, we probably want to wait until after merging to start filling functions with calls to this new assert function).

**Comment by fingolfin** [comment]
@ChrisJefferson implemented something along this line on the master branch.
