### ISSUE TITLE
make clean does not work

### ISSUE THREAD

**Issue by olexandr-konovalov** [fingolfin/gap#90]
After building with HPC-GAP support, I had an error after calling `make clean` (and why all that checks are needed?):
```
checking size of long... 8
checking size of long long... 8
checking whether to enable HPC-GAP... yes
checking whether to enable debug mode... no
./configure: line 16678: syntax error near unexpected token `GMP,'
./configure: line 16678: `    AX_CHECK_LIBRARY(GMP, gmp.h, gmp, __gmpz_init)'
```
Fixed by rerunning autogen.sh

**Comment by fingolfin** [comment]
This looks as if you had a broken configure file for some reason, and fixed it by re-running autogen.sh. Not sure there is anything to "fix" in this issue?

I am also not 100% sure what you mean with "and why all that checks are needed?" -- my guess is that you did "make clean" and it started to re-run `configure` and you are asking "why is it doing that" ? Well that is a side effect of the "maintainer" mode, in which `configure` is automatically re-run if `configure.ac` was modified -- this happens first thing for any call to `make`, as the fresh `configure` run might change settings that in turn affect `make`. The code doing that is generic -- even though `make clean` likely is not affected by such a re-run (but it might be in the future...)

**Comment by olexandr-konovalov** [comment]
OK, then I will close this. Yes, my question  "and why all that checks are needed?" what about that.
