### ISSUE TITLE
Complete documentation in README.buildsys.md

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#92]
See https://github.com/fingolfin/gap/blob/hpc-merge/README.buildsys.md

**Comment by markuspf** [comment]
It would be useful to document common tasks like "How do I add a sourcefile" or "How do I add a target" (in particular which files should be edited etc).

**Comment by fingolfin** [comment]
@markuspf Did this some time ago.

Closing this -- if people want changes here, they should request them via specific new issues.
