### ISSUE TITLE
Add a way to quickly detect on GAP / library level if running HPC-GAP or not

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#99]
At some point, we'll want to have code that does slightly different things depending on whether it runs in GAP or HPC-GAP. So it would be great if there was a reliable way to detect it, so that one could write like this:
```
  if IsBound(GAPInfo.IsHPCGAP then
     myList := AtomicList( myList );
  fi;
```
Or if there is such a way already, then perhaps it could be documented more clearly, so that it can be found more easily?

Of course one could also check for some function that is only available in HPC-GAP, but (a) that is less concise, and (b) it could go wrong, e.g. if that function for some reason also appears in regular GAP.

**Comment by ChrisJefferson** [comment]
I'm not sure of a clear way of detecting HPC-GAP, we should define one.

I think I would export some new variable rather than put this in `GAPInfo`, because I imagine we'll want it to exist very early, possibly before `GAPInfo` is created. The easiest option might just be a `IsHPCGAP()` kernel function.

**Comment by fingolfin** [comment]
The drawback of a function is that it is not usable in code that is meant to work in older GAP versions, too - like in a package. Though I guess one could perhaps write `if IsBound(IsHPCGAP) and IsHPCGAP() then ...`?

**Comment by ChrisJefferson** [comment]
good point. In that case, we could just define bind a global variable `IsHPCGAP` to some constant (I suggest something like the string `"yes"`, so people don't accidentally write `if(IsHPCGAP) ... `

**Comment by fingolfin** [comment]
Resolved by defining the global var `HPCGAP` early in the kernel.
